### ISSUE TITLE
Consider DeferredViewAttributes

### ISSUE THREAD

**Issue by hemendra-sharma** [Backbase/DeferredResources#42]
A wrapper that contains different view attributes like text, text color, visibility, etc. 

```
@DataApi
public class DeferredViewAttributes private constructor(
    public val text: DeferredText,
    public val visibility: DeferredInteger,
    public val textColor: DeferredColor,
    public val image: DeferredDrawable,
    public val backgroundColor: DeferredColor
) {
   .
   .
   .
}
```

This way it is possible to encapsulate multiple properties of a view within a single block.

```
title = DeferredViewAttributes {
    text = DeferredText.Constant("My customised title")
    textColor = DeferredColor.Resource(R.color.colorPrimary)
    visibility = DeferredInteger.Constant(Visibility.GONE)
}

image = DeferredViewAttributes {
    image = DeferredDrawable.Resource(R.drawable.my_custom_image)
    backgroundColor = DeferredColor.Resource(R.color.backgroundOnPrimary)
}
```

**Comment by diederick-backbase** [comment]
I like the concept but I can't foresee yet if takes away part of the freedom we have now using style elements

**Comment by drewhamilton** [comment]
This concept is interesting. It raises a lot of questions for me. Would you have a different `*ViewAttributes` for each type of View subclass? The most common View subclasses have probably dozens of attributes—are they all included? Which properties make sense to defer (e.g., what's the use-case for deferring resolution of visibility; doesn't that belong in the view layer)? How do you handle mutually exclusive attributes, like the different ways TextView autosizing can be applied?

All these questions can have opinionated answers, but I'm not comfortable taking on those opinions in this library—whose only opinion right now is that declaring resources should be decoupled from resolving them. I'd encourage you to explore this concept in an auxiliary library instead.
