### ISSUE TITLE
Question: Lint check

### ISSUE THREAD

**Issue by emartynov** [Backbase/DeferredResources#93]
Super nice approach to decouple platform resources from common code.

Have you considered writing lint rules to check that args match resource patterns?

**Comment by drewhamilton** [comment]
The idea has come up but I'm not sure how it would work in the typical case where the value is resolved with arguments separately from where it's declared: The compiler has no way of knowing at the resolution site how the `DeferredFormattedString` was constructed, and thus what arguments it requires.

Perhaps an annotation indicating the required arguments? `@RequiredArgs([String::class, Int::class, etc.])` – seems cumbersome.

**Comment by emartynov** [comment]
Let me check how lint does it when it finds `Context.getString`. I assume it should warn the place of the declaration and not the place where it is resolved.

**Comment by drewhamilton** [comment]
For `Context.getString`, the resource ID and the arguments are always in the same place, so lint can easily compare them. For `DeferredFormattedString` this is not the case: the format or resource ID is passed to the constructor, while the format args are passed to `resolve`.

They could be near each other for callers who use `DeferredFormattedString.withFormatArgs`, maybe a lint rule could be made for that case? Might be too narrow of a case to bother with it though.

**Comment by emartynov** [comment]
Yeah, the resolving is powerful but hardens the ability to detect such errors, unfortunately. 
In our case, all of the text resources know about parameters on creation (we use our own solution that looks like yours, except all things are in a constructor).

**Comment by emartynov** [comment]
Oke, sorry for the noice - I will close the ticket.
