### ISSUE TITLE
prepare-next-development-version release step is broken

### ISSUE THREAD

**Issue by drewhamilton** [Backbase/DeferredResources#97]
See [here](https://github.com/Backbase/DeferredResources/actions/runs/4639592876/jobs/8210812458). The most likely cause is that the `ACCESS_TOKEN` used to authenticate the Action is [expired](https://github.com/actions/checkout/issues/664#issuecomment-1186808305).

I don't have access to the repo's secrets (Settings/Environments) so I can't check on the existing token or update it. @donaldchickeme, can you confirm whether the existing `ACCESS_TOKEN` is expired?

**Comment by donaldchickeme** [comment]
Hey @drewhamilton, I have updated the PAT, could you try again?

**Comment by drewhamilton** [comment]
It worked! The falling step passed and the bumped version was [committed](https://github.com/Backbase/DeferredResources/commit/e4ad4fc855489802e10e98e1cee219bd85f79472).
